# Firmware Version: v2.06.4

try:
    FIELD_DATA_APP_PASS
except NameError:
    FIELD_DATA_APP_PASS = ""
try:
    ENABLE_FIRST_CHECKIN_CLAIM
except NameError:
    ENABLE_FIRST_CHECKIN_CLAIM = False
try:
    CLAIM_CONFIRM_DELAY_S
except NameError:
    CLAIM_CONFIRM_DELAY_S = 0

LOG_DIR = '/logs'

UNIT_ID_FILE = LOG_DIR + '/unit_id.txt'
MACHINE_ID_FILE = LOG_DIR + '/machine_id.txt'
WORDPRESS_API_URL_FILE = LOG_DIR + '/wordpress_api_url.txt'
PROVISIONED_FLAG_FILE = LOG_DIR + '/provisioned.flag'
REMOTE_SETTINGS_STAGED_FILE = LOG_DIR + '/remote_settings.staged.json'
REMOTE_SETTINGS_APPLIED_FILE = LOG_DIR + '/remote_settings.applied.json'
REMOTE_SETTINGS_PREV_FILE = LOG_DIR + '/remote_settings.prev.json'
UNIT_NAME_FILE = '/logs/unit_name.txt'

LOG_FILE = LOG_DIR + '/lora.log'
ERROR_LOG_FILE = LOG_DIR + '/lora_errors.log'
FIELD_DATA_LOG = LOG_DIR + '/field_data.log'
DATA_HISTORY_LOG = LOG_DIR + '/data_history.log'

FIELD_DATA_DELIVERED_LOG = LOG_DIR + '/field_data.delivered.log'
FIELD_DATA_MAX_BYTES = 256 * 1024
FIELD_DATA_MAX_BATCH = 50
FIELD_DATA_SEND_INTERVAL = 30
FIELD_DATA_BACKOFF_S = 10
FIELD_DATA_GZIP = True

UNIT_ID = "None"
UNIT_Name = "No Device Name"
NODE_TYPE = 'base'
FIRMWARE_VERSION = "v2.00.1c"

WORDPRESS_API_URL = ""
WORDPRESS_USERNAME = "agadmin"
WORDPRESS_PASSWORD = "Pepper-1"

MACHINE_ID = None
UNIT_PROVISIONED = False
TMON_ADMIN_API_URL = "https://tmonsystems.com"
PROVISION_CHECK_INTERVAL_S = 30
PROVISION_MAX_RETRIES = 60
WIFI_ALWAYS_ON_WHEN_UNPROVISIONED = True
WIFI_DISABLE_AFTER_PROVISION = True
PROVISIONED_FLAG_FILE = '/logs/provisioned.flag'
REMOTE_SETTINGS_STAGED_FILE = '/logs/remote_settings.staged.json'
REMOTE_SETTINGS_APPLIED_FILE = '/logs/remote_settings.applied.json'
REMOTE_SETTINGS_PREV_FILE = '/logs/remote_settings.prev.json'
UNIT_ID_FILE = '/logs/unit_id.txt'
MACHINE_ID_FILE = '/logs/machine_id.txt'
LAST_FIRMWARE_CHECK_FILE = '/logs/fw_last_check.txt'
OTA_PENDING_FILE = '/logs/ota_pending.flag'

ENABLE_WIFI = True
ENABLE_LORA = True
ENABLE_OLED = True
GPS_ENABLED = True
ENGINE_ENABLED = False

ENABLE_sensorBME280 = True
i2cAddr_BME280 = 0x76
ENABLE_sensorDHT11 = False
i2cAddr_DHT11 = 0x76
ENABLE_sensorLTR390 = False
light_i2c_address = 0x53
ENABLE_MPU925x = False
motion_i2c_address = 0x68
ENABLE_sensorSGP40 = False
voc_i2c_address = 0x59
ENABLE_sensorTSL2591 = False
lux_i2c_address = 0x29

SYS_VOLTAGE_PIN = 3
LED_PIN = 21
RELAY_PIN1 = 17
RELAY_PIN2 = 18
RELAY_PIN3 = None
RELAY_PIN4 = None
RELAY_PIN5 = None
RELAY_PIN6 = None
RELAY_PIN7 = None
RELAY_PIN8 = None
I2C_A_SCL_PIN = 33
I2C_A_SDA_PIN = 34
I2C_B_SCL_PIN = 38
I2C_B_SDA_PIN = 39
SPI_BUS = 1
CLK_PIN = 35
MOSI_PIN = 36
MISO_PIN = 37
CS_PIN = 14
IRQ_PIN = 4
RST_PIN = 40
BUSY_PIN = 13
CH1_TX_PIN = 4
CH1_RX_PIN = 5
CH2_TX_PIN = 6
CH2_RX_PIN = 7

DEBUG = False
DEBUG_SAMPLING = False
DEBUG_BME280 = False
DEBUG_DHT11 = False
DEBUG_TEMP = False
DEBUG_BAR = False
DEBUG_HUMID = False
DEBUG_LORA = True
DEBUG_WIFI_CONNECT = False
DEBUG_OTA = True
DEBUG_PROVISION = True
DEBUG_DISPLAY = False
DEBUG_BASE_NODE = True
DEBUG_REMOTE_NODE = True
DEBUG_WIFI_NODE = False
DEBUG_WPREST = False
DEBUG_FIELD_DATA = True
DEBUG_RS485 = False

DEBUG_WIFI = DEBUG_WIFI_CONNECT
DEBUG_OLED = DEBUG_DISPLAY
DEBUG_WP_REST = DEBUG_WPREST
DEBUG_PROV = DEBUG_PROVISION

ENGINE_FORCE_DISABLED = True
ENABLE_RS485 = False
ENABLE_ENGINE_CONTROLLER = False
ENGINE_POLL_INTERVAL_S = 30
ENGINE_DEV_ADDR = 1
ENGINE_DEV_COUNT = 1
ENGINE_SAMPLE_RATE = 30
ENGINE_KEEPALIVE = 5
ENGINE_PUMP1_COIL = 0
ENGINE_PUMP2_COIL = 1
COMM_BAUD = 9600
COMM_PARITY = None
COMM_STOP_BITS = 1

ENABLE_RELAY1 = True
ENABLE_RELAY2 = True
ENABLE_RELAY3 = False
ENABLE_RELAY4 = False
ENABLE_RELAY5 = False
ENABLE_RELAY6 = False
ENABLE_RELAY7 = False
ENABLE_RELAY8 = False
RELAY_RUNTIME_LIMITS = {
    1: 720,
    2: 720
}

WIFI_SSID = "house of nonsense"
WIFI_PASS = "bluebread219"
WIFI_CONN_RETRIES = 5
WIFI_BACKOFF_S = 15
WIFI_SIGNAL_SAMPLE_INTERVAL_S = 30

nextLoraSync = 100
LORA_SYNC_WINDOW = 2
LORA_SLOT_SPACING_S = LORA_SYNC_WINDOW
LORA_CHECK_IN_MINUTES = 5
LORA_INIT_RETRY_BACKOFF_S = 1
LORA_HARD_REBOOT_ERR_CODES = [-2]
LORA_ERR_PERSIST_REBOOTS = 2
ERROR_STATE_FILE = LOG_DIR + '/last_error.state'
LORA_REMOTE_INFO_LOG = LOG_DIR + '/remote_info.log'
LORA_HMAC_ENABLED = True
LORA_HMAC_SECRET = ''
LORA_HMAC_COUNTER_FILE = LOG_DIR + '/lora_ctr.json'
LORA_REMOTE_COUNTERS_FILE = LOG_DIR + '/remote_ctr.json'
LORA_HMAC_REJECT_UNSIGNED = True
LORA_HMAC_REPLAY_PROTECT = True
LORA_ENCRYPT_ENABLED = True
LORA_ENCRYPT_SECRET = ''
FREQ = 915.0
BW = 125.0
SF = 12
CR = 7
SYNC_WORD = 0xF4
POWER = 14
CURRENT_LIMIT = 140.0
PREAMBLE_LEN = 12
CRC_ON = True
TCXO_VOLTAGE = 1.8
USE_LDO = True
CAD_SYMBOLS = 8
LORA_CAD_BACKOFF_S = 2
LORA_CAD_BACKOFF_MAX_S = 30

LAST_ERROR_CODE = 0
LAST_ERROR_NAME = ''
LAST_ERROR_TS = None
TELEMETRY_INCLUDE_LAST_ERROR = True
ERROR_COUNT_RESET_INTERVAL_S = 3600

GPS_SOURCE = 'manual'
GPS_LAT = None
GPS_LNG = None
GPS_ALT_M = None
GPS_ACCURACY_M = None
GPS_LAST_FIX_TS = None
GPS_OVERRIDE_ALLOWED = True
GPS_BROADCAST_TO_REMOTES = True
GPS_ACCEPT_FROM_BASE = True

OLED_UPDATE_INTERVAL_S = 10
OLED_SCROLL_ENABLED = False
OLED_PAGE_ROTATE_INTERVAL_S = 30
OLED_HEADER_HEIGHT = 16
OLED_FOOTER_HEIGHT = 12
DISPLAY_NET_BARS = True
OLED_HEADER_FLIP_S = 4

SAMPLE_TEMP = True
COMPARE_TEMP = True
SAMPLE_BAR = True
COMPARE_BAR = True
SAMPLE_HUMID = True
COMPARE_HUMID = True
SAMPLE_LIGHT = False
SAMPLE_VOC = False
SAMPLE_LUX = False

ENABLE_FROSTWATCH = False
FROSTWATCH_ACTIVE_TEMP = 70
FROSTWATCH_ALERT_TEMP = 42
FROSTWATCH_ACTION_TEMP = 38
FROSTWATCH_STANDDOWN_TEMP = 40

ENABLE_HEATWATCH = False
HEATWATCH_ACTIVE_TEMP = 90
HEATWATCH_ALERT_TEMP = 100
HEATWATCH_ACTION_TEMP = 110
HEATWATCH_STANDDOWN_TEMP = 105

SYS_VOLTAGE_MAX = 5.0
SYS_VOLTAGE_SAMPLE_INTERVAL_S = 60

OTA_ENABLED = True
OTA_BACKUP_ENABLED = True
OTA_BACKUP_DIR = '/ota/backup'
OTA_MAX_RETRIES = 3
ALLOW_REMOTE_COMMANDS = True
RELAY_SAFETY_MAX_RUNTIME_MIN = 1440
OTA_VERSION_ENDPOINT = 'https://raw.githubusercontent.com/kevinnutt83/TMON/main/micropython/version.txt'
OTA_FIRMWARE_BASE_URL = 'https://raw.githubusercontent.com/kevinnutt83/TMON/main/micropython/'
OTA_MANIFEST_URL = OTA_FIRMWARE_BASE_URL + 'manifest.json'
OTA_MIN_VERSION = FIRMWARE_VERSION
OTA_REQUIRE_NEWER_VERSION = True
OTA_HASH_VERIFY = True
OTA_APPLY_INTERVAL_S = 5
OTA_RESTORE_ON_FAIL = True
OTA_MAX_FILE_BYTES = 256*1024
OTA_FILES_ALLOWLIST = [
    'main.py','lora.py','utils.py','sampling.py','settings.py','relay.py','oled.py','ota.py','wprest.py'
]
OTA_MANIFEST_SIG_URL = OTA_MANIFEST_URL + '.sig'
OTA_MANIFEST_HMAC_SECRET = ''
OTA_ALLOW_DOWNGRADE = False
OTA_SKIP_OLDER_VERSION = True
OTA_ABORT_ON_HASH_MISMATCH = False
OTA_RETRY_ON_HASH_MISMATCH = True
OTA_MAX_HASH_FAILURES = 3
OTA_HASH_RETRY_INTERVAL_S = 2

OTA_VERSION_URLS = [
    'https://raw.githubusercontent.com/kevinnutt83/TMON/main/micropython/version.txt',
]
OTA_MANIFEST_URLS = [
    'https://raw.githubusercontent.com/kevinnutt83/TMON/main/micropython/manifest.json',
]
OTA_HTTP_HEADERS = {
    'User-Agent': 'TMON-Device/v2.06.0',
    'Accept': '*/*',
    'Cache-Control': 'no-cache',
    'Pragma': 'no-cache',
}

HTTP_TIMEOUT_S = 20
TLS_VERIFY = True

DEVICE_SUSPENDED = False
DEVICE_SUSPENDED_FILE = '/logs/suspended.flag'
LORA_NETWORK_NAME = 'tmon'
LORA_NETWORK_PASSWORD = '12345'
REMOTE_CHECKIN_INTERVAL_S = 300
REMOTE_CHECKIN_JITTER_S = 5

UC_CHECKIN_INTERVAL_S = 300

BASE_REMOTE_TABLE_FILE = '/logs/remotes.table.json'

FIELD_DATA_HMAC_ENABLED = False
FIELD_DATA_HMAC_SECRET = ''
FIELD_DATA_HMAC_INCLUDE_KEYS = ['unit_id','firmware_version','node_type']
FIELD_DATA_HMAC_TRUNCATE = 32

TMON_ADMIN_CONFIRM_TOKEN = ''

PLAN = ""

PROVISION_REBOOT_GUARD_FILE = LOG_DIR + '/provision_reboot.flag'

COMMANDS_POLL_INTERVAL_S = 20
COMMANDS_MAX_PER_POLL = 10
COMMAND_CONFIRM_DELAY_S = 0.2

APPLY_STAGED_SETTINGS_ON_BOOT = True
APPLY_STAGED_SETTINGS_ON_SYNC = True
STAGED_SETTINGS_KEYS_ALLOW = [
    'WORDPRESS_API_URL','TMON_ADMIN_API_URL','NODE_TYPE','UNIT_Name','PLAN',
    'ENABLE_WIFI','ENABLE_LORA','ENABLE_OLED','DEVICE_SUSPENDED',
    'WIFI_SSID','WIFI_PASS','WIFI_CONN_RETRIES','WIFI_BACKOFF_S',
    'OTA_ENABLED','OTA_CHECK_INTERVAL_S','OTA_APPLY_INTERVAL_S',
    'OTA_VERSION_ENDPOINT','OTA_MANIFEST_URL',
    'SAMPLE_TEMP','SAMPLE_BAR','SAMPLE_HUMID','SYS_VOLTAGE_SAMPLE_INTERVAL_S',
    'GPS_ENABLED','GPS_SOURCE','GPS_LAT','GPS_LNG','GPS_ALT_M','GPS_ACCURACY_M',
    'FIELD_DATA_HMAC_ENABLED','FIELD_DATA_HMAC_SECRET',
    'DEBUG','DEBUG_PROVISION','DEBUG_LORA','DEBUG_WIFI','DEBUG_OTA',
    'ENGINE_ENABLED','ENGINE_FORCE_DISABLED','ENABLE_SENSORBME280',
    'RELAY_PIN1','RELAY_PIN2','RELAY_RUNTIME_LIMITS',
    'ENABLE_OLED','UNIT_Name'
]
STAGED_SETTINGS_KEYS_DENY = [
    'FIRMWARE_VERSION','MACHINE_ID'
]

COMMAND_ALIASES = {
    'relay_ctrl': 'relay_ctrl',
    'set_var': 'set_var',
    'run_func': 'run_func',
    'firmware_update': 'firmware_update'
}

OTA_VERSION_ENDPOINT = OTA_VERSION_ENDPOINT
OTA_MANIFEST_URL = OTA_MANIFEST_URL
OTA_FIRMWARE_BASE_URL = OTA_FIRMWARE_BASE_URL

ADMIN_REGISTER_PATH = '/wp-json/tmon-admin/v1/device/register'
ADMIN_STATUS_PATH = '/wp-json/tmon-admin/v1/device/status'
ADMIN_SETTINGS_PATH = '/wp-json/tmon-admin/v1/device/settings'
ADMIN_CONFIRM_PATH = '/wp-json/tmon-admin/v1/device/confirm'
ADMIN_CONFIRM_APPLIED_PATH = '/wp-json/tmon-admin/v1/device/confirm-applied'

ADMIN_V2_CHECKIN_PATH = '/wp-json/tmon-admin/v2/device/checkin'
ADMIN_V2_ACK_PATH = '/wp-json/tmon-admin/v2/device/ack'

UC_DEVICE_COMMANDS_PATH = '/wp-json/tmon/v1/device/commands'
UC_DEVICE_COMMAND_CONFIRM_PATH = '/wp-json/tmon/v1/device/command/confirm'
UC_SETTINGS_STAGED_PATH = '/wp-json/tmon/v1/admin/device/settings-staged'
UC_SETTINGS_APPLIED_PATH = '/wp-json/tmon/v1/admin/device/settings-applied'

REST_HEADER_ADMIN_KEY = 'X-TMON-ADMIN'
REST_HEADER_HUB_KEY = 'X-TMON-HUB'
REST_HEADER_READ_KEY = 'X-TMON-READ'
REST_HEADER_CONFIRM = 'X-TMON-CONFIRM'

# Additions for LoRa OTA
LORA_CHUNK_SIZE = 200
OTA_TEMP_FILE = '/ota_temp.py'
