#!/usr/bin/env python3
"""
Generate micropython/manifest.json by hashing files in micropython/.

Usage:
  python scripts/generate_manifest.py [--commit] [--sig-secret ENV_VAR_NAME]

If --commit is provided and running in a git repo with GITHUB_TOKEN available in the environment,
the script will git-add and commit the updated manifest (useful in CI).
"""
import os
import sys
import argparse
import json
import hashlib
import hmac

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))


def find_mp_dir():
    here = os.path.abspath(os.path.dirname(__file__))
    candidates = (
        os.path.join(here, '..', 'micropython'),
        os.path.join(here, 'micropython'),
        os.path.join(os.getcwd(), 'micropython'),
        os.path.abspath('micropython'),
    )
    for path in candidates:
        path = os.path.abspath(path)
        if os.path.isdir(path) and os.path.exists(os.path.join(path, 'settings.py')):
            return path
    raise SystemExit('micropython/ firmware directory not found')


MP_DIR = find_mp_dir()
MANIFEST_PATH = os.path.join(MP_DIR, 'manifest.json')
SIG_PATH = MANIFEST_PATH + '.sig'

def sha256_hex(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()

SKIP_NAMES = {'manifest.json', 'manifest.json.bak', 'manifest.json.sig', 'manifest.py', 'pwd'}
SKIP_SUFFIXES = ('.pyc', '.bak', '~')
SKIP_DIRS = {'__pycache__', '.git'}

REQUIRED_LIB_FILES = {
    'lib/_sx126x.py',
    'lib/sx1262.py',
    'lib/sx126x.py',
    'lib/ssd1306.py',
    'lib/BME280.py',
    'lib/dht.py',
    'lib/urequests.py',
}

def is_device_file(rel):
    rel = rel.replace('\\', '/')
    if rel.startswith('lib/'):
        return rel in REQUIRED_LIB_FILES
    return rel.endswith('.py') or rel == 'version.txt'


def build_manifest(mp_dir=None, version=None):
    mp_dir = os.path.abspath(mp_dir or MP_DIR)
    files = {}
    for root, dirs, filenames in os.walk(mp_dir):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        if '.git' in root.split(os.sep):
            continue
        for fn in filenames:
            rel = os.path.relpath(os.path.join(root, fn), mp_dir)
            if rel in SKIP_NAMES or os.path.basename(rel) in SKIP_NAMES:
                continue
            if rel.endswith(SKIP_SUFFIXES) or rel.startswith('.'):
                continue
            if any(rel.endswith(suffix) for suffix in SKIP_SUFFIXES):
                continue
            if not is_device_file(rel):
                continue
            path = os.path.join(root, fn)
            files[rel.replace('\\','/')] = 'sha256:' + sha256_hex(path)
    manifest = {
        'name': 'tmon-micropython',
        'version': version or read_version(mp_dir),
        'description': 'TMON MicroPython firmware manifest',
        'files': files
    }
    return manifest

def read_version(mp_dir=None):
    vfile = os.path.join(mp_dir or MP_DIR, 'version.txt')
    try:
        with open(vfile, 'r') as f:
            return f.read().strip()
    except Exception:
        return 'v2.00.4h'


def emit_version(mp_dir, version):
    path = os.path.join(mp_dir, 'version.txt')
    with open(path, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(str(version).strip() + '\n')
    print('Wrote', path)
    return path


def emit_firmware_manifest_py(mp_dir, version):
    path = os.path.join(mp_dir, 'manifest.py')
    lines = [
        '# Auto-generated by scripts/generate_manifest.py - do not edit',
        '# Files are deployed as filesystem modules, not frozen.',
        '# version %s' % str(version).strip(),
        '# Intentionally empty of freeze()/module() entries.',
        '',
    ]
    with open(path, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(lines))
    print('Wrote', path)
    return path

def emit_manifest(manifest, path=MANIFEST_PATH):
    # Backup previous manifest
    try:
        if os.path.exists(path):
            os.replace(path, path + '.bak')
    except Exception:
        pass
    with open(path, 'w') as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    print(f'Wrote manifest to {path} ({len(manifest["files"])} files)')

def emit_sig(manifest, path, secret_env='OTA_MANIFEST_HMAC_SECRET'):
    secret_name = secret_env
    secret = os.environ.get(secret_name, '') if secret_name else ''
    if not secret:
        print('No HMAC secret present; skipping signature generation.')
        return
    # Use canonical JSON representation: sorted keys, separators without whitespace
    canonical = json.dumps(manifest, separators=(',', ':'), sort_keys=True).encode('utf-8')
    mac = hmac.new(secret.encode('utf-8'), canonical, hashlib.sha256).hexdigest().lower()
    with open(path, 'w') as sf:
        sf.write(mac)
    print(f'Wrote manifest signature to {path}')

def git_commit(path, message='chore: update micropython manifest'):
    # best-effort: only attempt if git available and in repo
    try:
        import subprocess
        subprocess.check_call(['git', 'add', path])
        subprocess.check_call(['git', 'commit', '-m', message])
        print('Committed manifest via git')
    except Exception as e:
        print('Git commit skipped/failed:', e)

def manifest_equal(manifest, path):
    """
    Return True if the JSON manifest at 'path' is semantically equal to 'manifest' dict.
    """
    try:
        if not os.path.exists(path):
            return False
        with open(path, 'r') as f:
            existing = json.load(f)
        return existing == manifest
    except Exception:
        return False

def sig_equal(manifest, sig_path, secret_env='OTA_MANIFEST_HMAC_SECRET'):
    secret = os.environ.get(secret_env, '')
    if not secret:
        # no secret provided → cannot validate, treat as equal to avoid false failures
        return True
    try:
        if not os.path.exists(sig_path):
            return False
        canonical = json.dumps(manifest, separators=(',', ':'), sort_keys=True).encode('utf-8')
        mac = hmac.new(secret.encode('utf-8'), canonical, hashlib.sha256).hexdigest().lower()
        with open(sig_path, 'r') as sf:
            existing = sf.read().strip().lower()
        return existing == mac
    except Exception:
        return False

def sync_settings_version(version_value, mp_dir=None):
    settings_path = os.path.join(mp_dir or MP_DIR, 'settings.py')
    if not os.path.exists(settings_path):
        return
    try:
        with open(settings_path, 'r') as fh:
            text = fh.read()
        marker = 'FIRMWARE_VERSION ='
        if marker not in text:
            return
        start = text.index(marker)
        end = text.find('\n# ============================================================', start)
        if end == -1:
            end = len(text)
        replacement = 'FIRMWARE_VERSION = _read_firmware_version()'
        if 'def _read_firmware_version()' not in text:
            replacement = f'FIRMWARE_VERSION = "{version_value}"'
        text = text[:start] + replacement + text[end:]
        with open(settings_path, 'w') as fh:
            fh.write(text)
    except Exception:
        pass


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--commit', action='store_true', help='git commit the new manifest (requires git & token in CI)')
    ap.add_argument('--version', help='firmware version to write before hashing')
    ap.add_argument('--out-dir', help='firmware output directory; defaults to resolved micropython/')
    ap.add_argument('--sig-secret-env', default='OTA_MANIFEST_HMAC_SECRET', help='Env var name to read HMAC secret from for .sig generation')
    ap.add_argument('--check-only', action='store_true', help='Build and compare manifest+sig and exit non-zero if different (CI friendly)')
    args = ap.parse_args()

    mp_dir = os.path.abspath(args.out_dir) if args.out_dir else find_mp_dir()
    if os.path.basename(mp_dir) != 'micropython' or not os.path.exists(os.path.join(mp_dir, 'settings.py')):
        print('firmware output directory must be a micropython/ directory', file=sys.stderr)
        sys.exit(2)
    manifest_path = os.path.join(mp_dir, 'manifest.json')
    sig_path = manifest_path + '.sig'
    firmware_manifest_path = os.path.join(mp_dir, 'manifest.py')
    print('Firmware dir:', mp_dir)

    version = args.version or read_version(mp_dir)
    if args.check_only:
        manifest = build_manifest(mp_dir, version=version)
        ok_m = manifest_equal(manifest, manifest_path)
        ok_v = os.path.exists(os.path.join(mp_dir, 'version.txt')) and read_version(mp_dir) == version
        ok_f = os.path.exists(firmware_manifest_path)
        ok_s = sig_equal(manifest, sig_path, args.sig_secret_env)
        if ok_m and ok_v and ok_f and ok_s:
            print('Firmware artifacts are up-to-date.')
            sys.exit(0)
        if not ok_m:
            print('Manifest file is out-of-date or missing.')
        if not ok_v:
            print('Version file is out-of-date or missing.')
        if not ok_f:
            print('Firmware manifest.py is missing.')
        if not ok_s:
            print('Manifest signature is out-of-date or missing (secret provided).')
        sys.exit(1)

    emit_version(mp_dir, version)
    manifest = build_manifest(mp_dir, version=version)
    emit_manifest(manifest, manifest_path)
    emit_firmware_manifest_py(mp_dir, version)
    emit_sig(manifest, sig_path, secret_env=args.sig_secret_env)
    sync_settings_version(version, mp_dir)

    if args.commit:
        git_commit(manifest_path)
        if os.path.exists(sig_path):
            git_commit(sig_path)

if __name__ == '__main__':
    main()
